---
engines:
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript
      - php
  eslint:
    enabled: true
  fixme:
    enabled: true
    config:
      strings:
      - BUG
      - FIXME
      - HACK
      - NANGA
      - TODO
  phpmd:
    enabled: true
    checks:
      CleanCode/StaticAccess:
        enabled: false
      Controversial/Superglobals:
        enabled: false
  scss-lint:
    enabled: true
  phpcodesniffer:
    enabled: false
    config:
      standard: "PSR1,PSR2"
  stylelint:
    enabled: true
  shellcheck:
    enabled: true
ratings:
  paths:
  - "**.css"
  - "**.less"
  - "**.scss"
  - "**.sss"
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.sh"
exclude_paths:
- build/
- node_modules/
- vendor/
